package pt.ua.deti.tqs.airQuality.frontend;
// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.List;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@ExtendWith(SeleniumJupiter.class)
@Disabled
public class TestSearchWeatherTest {

  @Test
  void testSearchWeather(FirefoxDriver driver) {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1850, 1053));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".card:nth-child(2) .btn"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("Air Quality"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".card:nth-child(2) .btn")).click();
    driver.findElement(By.name("country")).click();
    {

      WebDriverWait wait;
      wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      wait.until(webDriver -> webDriver.findElement(By.xpath("//option[. = 'Portugal']")).getText().equals("Portugal"));
      WebElement dropdown = driver.findElement(By.name("country"));
      dropdown.findElement(By.xpath("//option[. = 'Portugal']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(110)")).click();
    driver.findElement(By.name("state")).click();
    {
      WebElement dropdown = driver.findElement(By.name("state"));
      dropdown.findElement(By.xpath("//option[. = 'Aveiro']")).click();
    }
    driver.findElement(By.cssSelector(".select:nth-child(3) > option:nth-child(2)")).click();
    driver.findElement(By.name("city")).click();
    {
      WebElement dropdown = driver.findElement(By.name("city"));
      dropdown.findElement(By.xpath("//option[. = 'Agueda']")).click();
    }
    driver.findElement(By.cssSelector(".mb-4 > option:nth-child(2)")).click();
    {
      String value = driver.findElement(By.name("country")).getAttribute("value");
      assertThat(value, is("Portugal"));
    }
    {
      String value = driver.findElement(By.name("state")).getAttribute("value");
      assertThat(value, is("Aveiro"));
    }
    {
      String value = driver.findElement(By.name("city")).getAttribute("value");
      assertThat(value, is("Agueda"));
    }
    driver.findElement(By.cssSelector(".btn-outline")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-outline"));
      assert(elements.size() > 0);
    }
  }
}
