package pt.ua.deti.tqs.airQuality.frontend;
// Generated by Selenium IDE

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.List;


@ExtendWith(SeleniumJupiter.class)
public class TestSearchAirQualityTest {

  @Test
  @Disabled
  void testSearchAirQuality(FirefoxDriver driver) {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1850, 1053));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".card:nth-child(1) > .card-body > .btn"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("Air Quality"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".card:nth-child(1) > .card-body > .btn")).click();
    driver.findElement(By.name("city")).click();
    driver.findElement(By.name("city")).sendKeys("Ovar");
    driver.findElement(By.name("country")).click();
    driver.findElement(By.name("country")).sendKeys("Portugal");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".text-2xl"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".stats:nth-child(1) > .stat-figure .swap-on"));
      assert(elements.size() > 0);
    }
  }
}
